# Generated by Django 3.0.8 on 2020-08-28 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20200828_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='follower',
            new_name='followers',
        ),
    ]
